# Commands
GCC=gcc
CP=cp
MKDIR=mkdir -v -p
RM=rm -f
RMDIR=rm -rf

# Paths
PLUGIN_PATH=/usr/lib/oculusd
BINARY_PATH=/usr/bin
LIBRARY_PATH=/usr/lib
MANPAGE_PATH=/usr/share/man/man
CONFIG_PATH=/etc/oculusd
DTD_PATH=/etc/oculusd

# Misc
INCLUDE_XML2=/usr/include/libxml2

# Flags
BINARY_GCC_FLAGS=-I$(INCLUDE_XML2) -g
LIBRARY_GCC_FLAGS=--shared -I$(INCLUDE_XML2) -fPIC
PLUGIN_GCC_FLAGS=--shared -lc -loculus -I$(INCLUDE_XML2) -fPIC
PLUGIN_LD_FLAGS=-L../src


